audio_play_sound(dk2,0,0)
show_message("wait thats not a banana thats a bartnana!!!!!!!!! OH FIDDLE STICKS!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
audio_play_sound(ow,0,0)
audio_stop_sound(lvl15music)
room_goto(room14)